### ISSUE TITLE
File Logging

### ISSUE THREAD

**Issue by cofirazak** [swarajkumarsingh/flutter_logger_plus#1]
Hi 👋
In the readme you say:
"File Logging: Optionally save logs to a file for later analysis."
But how to implement this?
Is there any example?

**Comment by swarajkumarsingh** [comment]
> Hi 👋 In the readme you say: "File Logging: Optionally save logs to a file for later analysis." But how to implement this? Is there any example?

Thank you for the problem; this feature has yet to be developed because I am focusing more on Golang and backend stuff and am unable to manage time for it; it would be wonderful if you could implement the functionality and submit a PR.

Blue Print for the feature:
- create a new function (storeLogs)
- Take the log prompt from the function parameter
- And if you want to store logs in firebase, redis, or in local storage(logs.txt)
- For Firebase, take the credentials from the user, and simply push the logs
- Same for the redis
- For local storage, take file path, and various permissions for read & write in android & ios, and push the logs in a spcific order
   {log:"message", DateTime: "date-time" ...}

Code for the function 
```
  void success(String prompt) bool {
    // get the firebase/redis credentials

    // push logs to firebase/redis

    // for local-storage
    // get the file path for log.txt
    // write a simple function to append the log in the file

    // return success bool
  }
```
